# Generated by Django 3.2.8 on 2022-05-19 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinfo',
            name='daily_time',
            field=models.DateField(db_column='daily_time', default=datetime.datetime(2022, 5, 19, 9, 52, 31, 41392), verbose_name='推荐时间'),
        ),
    ]
