# Generated by Django 3.2.8 on 2022-05-19 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_dailyinfo_daily_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinfo',
            name='daily_time',
            field=models.DateTimeField(db_column='daily_time', default=datetime.datetime(2022, 5, 19, 9, 55, 38, 933772), verbose_name='推荐时间'),
        ),
    ]
