# Generated by Django 3.2.8 on 2022-05-21 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_dailyinfo_daily_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='result',
            field=models.IntegerField(choices=[(0, '未违规'), (1, '违规')], default=0, verbose_name='处理结果'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='adminstrate',
            field=models.ForeignKey(db_column='adminstrate', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='imformer',
            field=models.ForeignKey(db_column='imformer', on_delete=django.db.models.deletion.CASCADE, related_name='imformer_id', to=settings.AUTH_USER_MODEL, verbose_name='举报人'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='isdealt',
            field=models.BooleanField(default=False, verbose_name='是否处理'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='range',
            field=models.CharField(max_length=20, verbose_name='书籍违规页范围'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='reported',
            field=models.ForeignKey(db_column='reported', on_delete=django.db.models.deletion.CASCADE, related_name='reported_id', to=settings.AUTH_USER_MODEL, verbose_name='被举报人'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='reportid',
            field=models.IntegerField(db_column='reportid', primary_key=True, serialize=False, verbose_name='举报编号'),
        ),
    ]
